server {
    listen 8002;
    server_name localhost;
    host 0.0.0.0;
    root ./YoupiBanane;
    client_max_body_size 10000000;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex on;
		upload_path www/uploads;
    }

    location /cgi-bin {
        root ./cgi-bin;
        allow_methods POST;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .bla;
    }
}